# Generated by Django 4.0.3 on 2022-04-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dizi Adı')),
                ('description', models.TextField(verbose_name='Dizi Açıklaması')),
                ('image', models.CharField(max_length=50, verbose_name='Dizi Resmi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('isPublished', models.BooleanField(default=True)),
            ],
        ),
    ]
