# Generated by Django 4.0.3 on 2022-04-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='isPublished',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='film eklenme tarihi'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='decription',
            field=models.TextField(verbose_name='film açıklaması'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(max_length=50, verbose_name='film resmi'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='film adı'),
        ),
    ]
