# Generated by Django 4.0.3 on 2022-04-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190907_1432'),
        ('movies', '0002_movie_ispublished_alter_movie_create_date_and_more'),
    ]

    operations = [
    ]
