# Generated by Django 4.0.3 on 2022-04-28 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_merge_20220428_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='decription',
        ),
    ]
